Job Offers/Controllers/JobssesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Job_Offers.Models;
using WebApplication5.Models;

namespace Job_Offers.Controllers
{
    public class JobssesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Jobsses
        public ActionResult Index()
        {
            var jobsses = db.Jobsses.Include(j => j.Category);
            return View(jobsses.ToList());
        }

        // GET: Jobsses/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Jobss jobss = db.Jobsses.Find(id);
            if (jobss == null)
            {
                return HttpNotFound();
            }
            return View(jobss);
        }

        // GET: Jobsses/Create
        public ActionResult Create()
        {
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "CategoryName");
            return View();
        }

        // POST: Jobsses/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Jobss jobss, HttpPostedFileBase upload)
        {
            string path;
            if (ModelState.IsValid && upload == null)
            {
                
                path = "No_Image_Available.jpg";

                
                jobss.JobImage = path;
                db.Jobsses.Add(jobss);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            if (ModelState.IsValid && upload != null)
            {
                path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                upload.SaveAs(path);
                jobss.JobImage = upload.FileName;
                db.Jobsses.Add(jobss);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "CategoryName", jobss.CategoryID);
            return View(jobss);
        }

        // GET: Jobsses/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Jobss jobss = db.Jobsses.Find(id);
            if (jobss == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "CategoryName", jobss.CategoryID);
            return View(jobss);
        }

        // POST: Jobsses/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Jobss jobss, HttpPostedFileBase upload)
        {
            
            if (ModelState.IsValid)
            {
                string oldPath = Path.Combine(Server.MapPath("~/Uploads"),jobss.JobImage);

                if (upload != null)
                {
                    System.IO.File.Delete(oldPath);
                    string path = Path.Combine(Server.MapPath("~/Uploads"), upload.FileName);
                    upload.SaveAs(path);
                    jobss.JobImage = upload.FileName;
                }                                
                
                db.Entry(jobss).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CategoryID = new SelectList(db.Categories, "ID", "CategoryName", jobss.CategoryID);
            return View(jobss);
            
        }

        // GET: Jobsses/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Jobss jobss = db.Jobsses.Find(id);
            if (jobss == null)
            {
                return HttpNotFound();
            }
            return View(jobss);
        }

        // POST: Jobsses/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Jobss jobss = db.Jobsses.Find(id);
            db.Jobsses.Remove(jobss);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Job Offers/Views/Jobsses/Create.cshtml
@model Job_Offers.Models.Jobss

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>انشاء وظيفة جديدة</h2>

@using (Html.BeginForm("Create", "Jobsses", FormMethod.Post, new {enctype="multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>الوظائف</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.JobTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JibContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JibContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JibContent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="upload" />
                @Html.ValidationMessageFor(model => model.JobImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "نوع الوظيفة", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="انشاء" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("الرجوع للقائمة السابقة", "Index")
</div>

Job Offers/Views/Jobsses/Delete.cshtml
@model Job_Offers.Models.Jobss

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>حذف</h2>

<h3>هل تريد حذف البيانات؟؟</h3>
<div>
    <h4>وظائف</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JibContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JibContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobImage)
        </dt>

        <dd>
            <img src="~/uploads/@Html.DisplayFor(model=>model.JobImage)"
                 class="thumbnail"
                 style="width: 100px; height:100px; margin-top:10px" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="حذف" class="btn btn-danger" /> |
            @Html.ActionLink("الرجوع للقائمة السابقة", "Index")
        </div>
    }
</div>

Job Offers/Views/Jobsses/Details.cshtml
@model Job_Offers.Models.Jobss

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>التفاصيل</h2>

<div>
    <h4>الوظائف</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.CategoryName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobTitle)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JobTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JibContent)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.JibContent)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.JobImage)
        </dt>

        <dd>
            <img src="~/uploads/@Html.DisplayFor(model=>model.JobImage)" 
                 class="thumbnail" 
                 style="width: 100px; height:100px; margin-top:10px" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("تعديل", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("الرجوع للقائمة السابقة", "Index")
</p>

Job Offers/Views/Jobsses/Edit.cshtml
@model Job_Offers.Models.Jobss

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>تعديل</h2>

@using (Html.BeginForm("Edit", "Jobsses", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
                @Html.AntiForgeryToken()

    <div class="alert alert-danger" id="error-div" style="display:none">
        <span id="view-err">

        </span>
    </div>

    <div class="form-horizontal">
        <h4>الوظائف</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.JobImage)

        <div class="form-group">
            @Html.LabelFor(model => model.JobTitle, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JobTitle, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JobTitle, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JibContent, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.JibContent, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.JibContent, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.JobImage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="upload" id="myimage" />
                @Html.ValidationMessageFor(model => model.JobImage, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryID, "نوع الوظيفة", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CategoryID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="تعديل" class="btn btn-default" id="save" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("الرجوع للقائمة السابقة", "Index")
</div>

<script src="~/Scripts/jquery.js"></script>
<script>
    $(function () {
        $("#save").click(function () {
            if ($("#myimage").val() != "") {
            var filename = document.getElementById("myimage").value;
            var exImage = filename.substr(filename.lastIndexOf(".") + 1);
            var validex = ['jpg', 'png', 'gif', 'bmp'];
            if ($.inArray(exImage, validex) == -1) {
                $("#error-div").fadeIn();
                $("#view-err").append("الرجاء اختيار صورة بامتداد معروف");
                return false;
            }
            var filesize = document.getElementById("myimage").files[0].size / 1024 / 1024;
            if (filesize > 2) {
                $("#error-div").fadeIn();
                $("#view-err").append("الرجاء اختيار صورة حجمها اقل من 2 ميجابايت");
                return false;
            }
         }
        
        });
    });
</script>

Job Offers/Views/Jobsses/Index.cshtml
@model IEnumerable<Job_Offers.Models.Jobss>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_MainLayout.cshtml";
}

<h2>الوظائف</h2>

<p>
    @Html.ActionLink("انشاء وظيفة جديدة", "Create")
</p>
<table class="table table-stripped table-bordered table-hover">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Category.CategoryName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobTitle)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JibContent)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.JobImage)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Category.CategoryName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JobTitle)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.JibContent)
        </td>
        <td>
            <img src="~/Uploads/@Html.DisplayFor(model=>item.JobImage)"
                 class="thumbnail"
                 style="width:48px; height:48px" />
        </td>
        <td>
            @Html.ActionLink("تعديل", "Edit", new { id=item.Id }) |
            @Html.ActionLink("تفاصيل", "Details", new { id=item.Id }) |
            @Html.ActionLink("حذف", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>